### ISSUE TITLE
如何验证 日期格式? 

### ISSUE THREAD

**Issue by jsbay** [D780/valparams#8]
```
date: { type: 'date', required: false, defValue: null, desc: '收集日期' }
````

校验后的时间会被格式化成 

```
date :Fri Jan 22 2021 08:00:00 GMT+0800 (China Standard Time)
```

请问应该怎么处理?

**Comment by D780** [comment]
格式化后的对象就是时间的对象（`validater.ret.all.date instanceof Date === true`）
如果要使用时间戳之类直接 .getTime() 等方式去获取即可

如下如果使用 `date`  的话如上述可以在 `range` 中用不同的时间格式去比对大小关系
`{type: 'date', range: {min: '2021-01-20', max: 1611652379889}}`

---

如果单纯的使用时间戳，其实也可以直接使用
不过 `range` 中的就是直接判断数值的大小了
`{type: 'number', range: {min: 1611100800000, max: 1611652379889}}`

**Comment by jsbay** [comment]
如果我需要存入数据的时间格式需要是 `yyyy-MM-dd`, 而我在接口请求中 发送给egg 接口的数据格式也是 `yyyy-MM-dd,` 我只是想校验一个这个参数是否符合时间格式,并不希望这个参数会被本插件格式成时间格式,那我唯一的做法就只能是将校验后的参数重新格式化成 `yyyy-MM-dd` 后,再存入数据库吗,只能这么做吗?是否有更优雅的方式去实现这个需求呢?

**Comment by D780** [comment]
转换是一个做法
也可以用字符串+正则表达式验证，这样就不涉及转换了只验证字符串的格式
如
`date: { type: 'string', range: { reg: /^[1-9]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/ }, trim: false}`

**Comment by jsbay** [comment]
好的,谢谢回答
